# Taplo configuration
# https://taplo.tamasfe.dev/configuration/

include = ["**/*.toml"]
exclude = [
  "node_modules/**",
  "target/**",
  "_site/**",
  "pnpm-*",
  "tauri/target/**",
  "tauri/gen/schemas/**",
]

[formatting]
align_entries = false
align_comments = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = true
compact_inline_tables = false
column_width = 80
indent_tables = false
indent_entries = false
trailing_newline = true
allowed_blank_lines = 1
crlf = false
